#!/usr/bin/env bash 
#
#       Convert an sm file into an QuickTime file...
#
function usage() {
    echo "sm2qt: usage:"
    echo "sm2qt [OPTIONS] smfile qtfilename [fps]"
    echo "If fps is not given, the default is 30"
    echo "If the input movie is stereo, then only the left hand frames (odd frames) are used." 
    echo "OPTIONS:"
    echo "-s/--stereo: interpret the input movie as stereo." 
}

function runecho(){
    echo "$@"
    "$@"
}
function errexit() {    
    echo '*************************************************'
    echo "ERROR: $1"
    echo '*************************************************'
    rm -f ${outframebase}_*png
    exit 1
}

stereo=false
if [ "$1" == "-s" ] || [ "$1" == "--stereo" ]; then 
    shift 1
    stereo=true
fi


tmpdir=/tmp/$USER/sm2mpg.tmp/
mkdir -p $tmpdir || errexit "Cannot make tmp directory $tmpdir"
if [ "$2" == "" ];  then
    usage
    errexit "Not enough args" 
fi

infile="$1"
if [ ${1:0:1} != '/' ]; then 
    infile=$(pwd)/$infile
fi
infiledot=$(expr ${#outfile} - 3)
if [ "${infile:$infiledot}" != '.sm' ]; then 
    errexit "Please specify an input movie name ending with '.sm'"
fi

outfile="$2"
if [ ${2:0:2} != '/' ]; then 
    outfile=$(pwd)/$outfile
fi
outfiledot=$(expr ${#outfile} - 4)
if [ "${outfile:$outfiledot}" != '.mov' ]; then 
    errexit "Please specify an outpu movie name ending with '.mov'"
fi

fps=${3:-30}

tmp=$(sminfo $infile)
if echo $tmp | grep Stereo >/dev/null 2>&1; then
    stereo=true
fi

ninput=$(sminfo $infile | grep Frames | cut "-d " -f2)

skip=1
if $stereo; then 
    skip=2
    ninput=$(expr $ninput / 2)
fi

# set -xv
outframebase=_$(basename $outfile | sed 's/.mov//')
pushd $tmpdir 
runecho sm2img -F png -s $skip $1 ${outframebase}_%05d.png || errexit "sm2img failed" 

if [ $skip != 1 ]; then 
    echo "renumbering output files..."
    framenum=0
    for frame in ${outframebase}_*png; do
        outnum=$(printf "%05d" $framenum)   
        outframe=${outframebase}_${outnum}.png
        if [ $outframe != $frame ]; then
            mv $frame ${outframebase}_${outnum}.png
        fi
        let framenum++
    done
fi

runecho ffmpeg -v -1 -mbd rd -trellis 2 -cmp 2 -subcmp 2 -g 300 -r $fps -i "${outframebase}_%05d.png" $outfile || errexit  "ffmpeg failed" 

rm -f $tmpdir/${outframebase}_*png
popd

#
#	Lots of files...
#

#echo "to clean up do this: "
#echo 'find $tmpdir -name "$2_junk_?????.rgb" -exec rm -f {} \;'
#find . -name "$2_junk_?????.rgb" -exec rm -f {} \;

