'\" "
'\" ASCI Visualization Project  "
'\" "
'\" Lawrence Livermore National Laboratory "
'\" Information Management and Graphics Group "
'\" P.O. Box 808, Mail Stop L-561 "
'\" Livermore, CA 94551-0808 "
'\" "
'\" For information about this project see: "
'\" 	http://www.llnl.gov/sccd/lc/img/  "
'\" "
'\" 	or contact: asciviz@llnl.gov "
'\" "
'\" For copyright and disclaimer information see: "
'\"     man llnl_copyright "	
'\" "
'\" $Id: smcat.1,v 1.1 2007/06/13 18:59:34 wealthychef Exp $ "
'\" $Name:  $ "
'\" "
.TH smcat 1
.SH NAME
smcat - create a streaming movie (sm) file from a set of input sm files.
.SH SYNOPSIS
smcat [options] outfile infile1 [infile2...]
.SH DESCRIPTION
smcat creates a new streaming movie (sm) file or set of output images from
frames selected from a set of input sm files.  OUTFILE specifies either
the name of the output file (options select the compression
mechanism for this file) OR a C-style \"image template\" consisting 
of a format specifier such as \"image_%04d.png\" which indicates both
the image basename \"image_\", the format of the numbering, here a 4-digit
0-padded number \"%04d\", and an image format \"png\". 
Finally, one or more INFILE files specify the source(s) for the movie frames.
The only restriction is that all the frames in all the 
input files must have the same dimensions (all combinations
of input compression settings are supported).
.PP
By default, all of the frames in each of the input files are
concatenated together in the order that the files appear
on the command line to form the output movie.
There is a naming extension that allows for a subset of
the images to be selected for inclusion for each input
file individually.  An input filename may take the
form: BASENAME[@start[@last[@step]]].  BASENAME is the
actual name of the sm file.  The name may be augmented
by one, two, or three fields separated by the '@' 
character.  These fields are interpreted as numbers
in ASCII form and specify the first frame, last frame, and inter
frame step.  These default to 0, (the last frame in the
file), and 1 respectively.  
.PP
For example, the input name:'myfile.sm@10@25@5' will 
cause frames 10, 15, 20
and 25 to be used from the input file.  Note: it is
legal for step to be negative, in which case, the order
of the frames will be reversed from the order in the
input file and the 'start' frame must be greater than
the 'end' frame number.
.PP
.SH OPTIONS
Options also exist for a variety of behaviors.  For a description, run
\"smcat -h\" for a full list with descriptions. 
.PP
.SH EXAMPLE
smcat -gz outfile.sm infile1.sm infile2.sm@10@20 infile3.sm@9@0@-1
.SH SEE ALSO
blockbuster(1), ifl2sm(1), img2sm(1), sm(4)
.SH ORIGIN
.RS
ASCI Visualization Project 
.RE
.RS
Lawrence Livermore National Laboratory
.RE
.RS
Information Management and Graphics Group
.RE
