'\" "
'\" ASCI Visualization Project  "
'\" "
'\" Lawrence Livermore National Laboratory "
'\" Information Management and Graphics Group "
'\" P.O. Box 808, Mail Stop L-561 "
'\" Livermore, CA 94551-0808 "
'\" "
'\" For information about this project see: "
'\" 	http://www.llnl.gov/sccd/lc/img/  "
'\" "
'\" 	or contact: asciviz@llnl.gov "
'\" "
'\" For copyright and disclaimer information see: "
'\"     man llnl_copyright "	
'\" "
'\" $Id: ps2sm.1,v 1.1 2007/06/13 18:59:34 wealthychef Exp $ "
'\" $Name:  $ "
'\" "
.TH ps2sm 1
.SH NAME
ps2sm - convert a PostScript or PDF file into a streaming movie (sm)
.SH SYNOPSIS
ps2sm psinfile smoutfile width [AA] [portrait]
.SH DESCRIPTION
ps2sm converts the pages of a PostScript of PDF file into a steaming
movie file.  The size of the streaming movie frames is given
by the WIDTH parameter and the aspect ratio of the input
file.
.PP
If the optional [AA] parameter is given, the image will first
be rasterized at 2x the final movie size and then convolved
down to the final image.  The result is a much smoother 
looking movie.
ps2sm requires enough disk space for all the PostScript pages to be
stored as individual files. 
.PP
If the optional [portrait] parameter is supplied, the
resulting image will not be rotated before being turned
into a movie frame.
.PP
This program uses the GhostScript command gs which must be 
installed and in the user's search path for ps2sm to work.
On most systems, this means that ps2sm can also handle
Adobe PDF files that gs can rasterize.
.SH EXAMPLE
ps2sm mypsfile.ps movie.sm 1024 AA portrait
.SH NOTES
A common us of this command is to convert a MS PowerPoint 
generated .ps file into a .sm file.  This can be done by
printing the .PPT file to a PostScript printer and saving 
the printer file to disk (.prn under Windows).
.SH SEE ALSO
img2sm(1), sm(4), gs(1)
.SH ORIGIN
.PP
.RS
ASCI Visualization Project 
.RE
.RS
Lawrence Livermore National Laboratory
.RE
.RS
Information Management and Graphics Group
.RE
